# https://alacritty.org/config-alacritty.html
#[terminal.shell]
#program = "/bin/zsh"
#args = ["-c", "start-tmux"]
[terminal]
osc52 = "OnlyCopy"

[keyboard]
bindings = [
  { key = "[", mods = "Control|Alt", chars = "\u001b[91;7u" }
]

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[general]
import=[
  "~/.config/alacritty/machine-specific.toml"
]
