# https://github.com/roosta/i3wsr?tab=readme-ov-file

[general]
display_property = "class"
default_icon = ""

[options]
remove_duplicates = true 
no_names = false         
no_icon_names = true     
focus_fix = true         

[aliases.class]
Brave="Brave"
terminal="Terminal"
firefox="Firefox"
Alacritty="Terminal"
Timeshift="Timeshift"
Localsend="Localsend"

# Fonts are inherited from i3 config
# https://fontawesome.com/search
# https://www.nerdfonts.com/cheat-sheet
[icons]
Brave = ""
Terminal= ""
Thunar=""
Localsend=""
Code=""
Blender=""
authenticator="󰢏"
Beeper=""
discord=""
Arandr=""
libreoffice-writer = ""
libreoffice-calc = ""
libreoffice-impress = ""
Timeshift=""
Mixxx=""
pavucontrol=""
resolve="󰿎"
baobab=""
bottles=""
ONLYOFFICE=""
resources=""
